version: "3.9"
services:    
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mdata:/data/db
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=root
        #     - MONGO_INITDB_ROOT_PASSWORD=root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/   
    
volumes:    
    mdata:
    
networks: 
    rentlynet:
        driver: bridge
