version: "3.9"
services:
    mongo1:
        container_name: mongo1
        image: mongo
        volumes:
        - mdata1:/data/db
        - ./rs-init.sh:/scripts/rs-init.sh
        networks:
        - mongors-network
        ports:
        - 27021:27017
        links:
        - mongo2      
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    mongo2:
        container_name: mongo2
        image: mongo
        volumes:
        - mdata2:/data/db
        networks:
        - mongors-network
        ports:
        - 27022:27017
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ] 
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/ 
networks:
  mongors-network:
    driver: bridge